<div class="page-header">
    <h1>Crear Usuario</h1>
</div>      
<?php View::content() ?>
<?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
<?php echo Form::hidden('usuario.id') ?>
<div class="control-group">
    <label for="usuario_login">Nombre de Usuario (Login)* : </label>
    <div class="controls">
        <?php echo Form::text('usuario.login') ?>
    </div>
</div>
<div class="control-group">
    <label for="usuario_clave">Contrase&ntilde;a* : </label>
    <div class="controls">
        <?php echo Form::pass('usuario.clave') ?>
    </div>
</div>
<div class="control-group">
    <label for="usuario_clave2">Volver a escribir Contrase&ntilde;a* : </label>
    <div class="controls">
        <?php echo Form::pass('usuario.clave2') ?>
    </div>
</div>
<div class="control-group">
    <label for="usuario_nombres">Nombre Completo* : </label>
    <div class="controls">
        <?php echo Form::text('usuario.nombres') ?>
    </div>
</div>
<div class="control-group">
    <label for="usuario_email">Correo Electronico* : </label>
    <div class="controls">
        <?php echo Form::text('usuario.email') ?>
    </div>
</div>
<div class="control-group">
    <label for="usuario_roles_id">Rol del Usuario* : </label>
    <div class="controls">
        <?php echo Form::dbSelect('usuario.roles_id', 'rol') ?>
    </div>
</div>
<div class="form-actions">
    <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
    <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
    </div>
<?php echo Form::close() ?>
